---
- name: Restart loki
  community.docker.docker_container:
    name: "{{ loki_container_name }}"
    state: started
    restart: true

- name: Restart promtail
  community.docker.docker_container:
    name: "{{ promtail_container_name }}"
    state: started
    restart: true

- name: Restart grafana
  community.docker.docker_container:
    name: "{{ grafana_container_name }}"
    state: started
    restart: true

- name: Restart tempo
  community.docker.docker_container:
    name: "{{ tempo_container_name }}"
    state: started
    restart: true

- name: Restart otel-collector
  community.docker.docker_container:
    name: "{{ otelcol_container_name }}"
    state: started
    restart: true

- name: Restart prometheus
  community.docker.docker_container:
    name: "{{ prometheus_container_name }}"
    state: started
    restart: true

- name: Restart logging stack
  community.docker.docker_compose_v2:
    project_src: /etc/ircfiber/logging
    state: present
    recreate: always
    env_files:
      - /etc/ircfiber/logging/logging.env