galaxy_info:
  author: IRC Fiber
  description: Base packages, timezone, time sync for IRC Fiber hosts
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - ircfiber
    - base
dependencies: []
