module ircfiber.build_version;

// Generated by scripts/generate-version.sh at 2026-08-14T09:20:38Z
enum GIT_HASH = "3d67df89505a501c8071e9660b3662c17d6b88e1";
enum GIT_SHORT = "3d67df8";
enum GIT_DESCRIBE = "3d67df8";
enum GIT_BRANCH = "main";
enum BUILD_TIME = "2026-08-14T09:20:38Z";
enum BUILD_HOST = "Kevins-MacBook-Pro.local";
enum VERSION = "0.3.0";
enum GIT_MESSAGE = "fix(engine): fall back to no-SASL when the server does not grant sasl";
enum GIT_COMMIT_URL = "https://github.com/kevinpostal/IRC_FIBER/commit/3d67df89505a501c8071e9660b3662c17d6b88e1";
