[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    warn
    Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*-json.log
    Parser            docker
    Tag               docker.*
    # See /fluent-bit.conf for why we exclude signoz/* containers.
    exclude_path      /var/lib/docker/containers/*ircfiber-fluent-bit*/*.log, /var/lib/docker/containers/*signoz*/*.log, /var/lib/docker/containers/*clickhouse*/*.log, /var/lib/docker/containers/*postgres*/*.log, /var/lib/docker/containers/*zookeeper*/*.log, /var/lib/docker/containers/*otel*/*.log
    Refresh_Interval  5
    Mem_Buf_Limit     50MB
    Skip_Long_Lines   On

[FILTER]
    Name      parser
    Match     docker.*
    Key_Name  log
    Parser    engine_json

[OUTPUT]
    Name              opentelemetry
    Host              otel-collector
    Port              4318
    Match             docker.*
    tls               off
