apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: ircfiber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          args: ["--save", ""]
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: ircfiber
spec:
  selector:
    app: redis
  ports:
    - port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: ircfiber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: ircfiber
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: ircfiber
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
