#!/usr/bin/env bash
# generate-version.sh — write common/source/ircfiber/build_version.d with current git info
set -eo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/common/source/ircfiber/build_version.d"

HASH=$(git -C "$ROOT" rev-parse HEAD 2>/dev/null || echo "unknown")
SHORT=$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")
# describe without dirty, then add dirty suffix only if non-build_version/buildInfo files are dirty
DESCRIBE_BASE=$(git -C "$ROOT" describe --always --long 2>/dev/null || echo "$SHORT")
if ! git -C "$ROOT" diff --quiet -- ':!common/source/ircfiber/build_version.d' ':!frontend/src/lib/buildInfo.ts' ':!public/dist' ':!backend/views/index.dt' 2>/dev/null; then DIRTY="-dirty"; fi
if ! git -C "$ROOT" diff --cached --quiet -- ':!common/source/ircfiber/build_version.d' ':!frontend/src/lib/buildInfo.ts' ':!public/dist' ':!backend/views/index.dt' 2>/dev/null; then DIRTY="-dirty"; fi
DESCRIBE="${DESCRIBE_BASE}${DIRTY}"
BRANCH=$(git -C "$ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || echo "unknown")
HOST=$(hostname 2>/dev/null || echo "unknown")
VERSION="0.3.0"

cat > "$OUT" <<EOF
module ircfiber.build_version;

// Generated by scripts/generate-version.sh at $TIME
enum GIT_HASH = "$HASH";
enum GIT_SHORT = "$SHORT";
enum GIT_DESCRIBE = "$DESCRIBE";
enum GIT_BRANCH = "$BRANCH";
enum BUILD_TIME = "$TIME";
enum BUILD_HOST = "$HOST";
enum VERSION = "$VERSION";
EOF
echo "version.d: $SHORT ($DESCRIBE) @ $BRANCH built $TIME"

# Frontend build info (for admin version display — same commit, separate builtAt)
FRONT_OUT="$ROOT/frontend/src/lib/buildInfo.ts"
cat > "$FRONT_OUT" <<EOF
// Generated by scripts/generate-version.sh at $TIME — do not edit
export const BUILD_INFO = {
  commit: "$HASH",
  short: "$SHORT",
  describe: "$DESCRIBE",
  branch: "$BRANCH",
  builtAt: "$TIME",
  builtHost: "$HOST",
  version: "$VERSION",
} as const;
EOF
echo "buildInfo.ts: $SHORT ($DESCRIBE) @ $BRANCH"
