---
- name: Deploy irc-fiber gateway
  hosts: ircfiber_gw
  become: true
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/../inventories/production/group_vars/vault.yml"
  roles:
    - role: gateway
