---
- name: Install & authenticate Tailscale
  hosts: ircfiber
  become: true
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/../inventories/production/group_vars/vault.yml"
  roles:
    - common
    - tailscale
