// Generated by scripts/generate-version.sh at 2026-08-22T00:18:13Z — do not edit
export const BUILD_INFO = {
  commit: "54278045eb05d9149ae5913beb3306a687c80fe4",
  short: "5427804",
  describe: "5427804",
  branch: "main",
  builtAt: "2026-08-22T00:18:13Z",
  builtHost: "Kevins-MacBook-Pro.local",
  version: "0.3.0",
  message: "fix(frontend): vite proxy for /admin/login + MessageList effect loop",
  commitUrl: "https://github.com/kevinpostal/IRC_FIBER/commit/54278045eb05d9149ae5913beb3306a687c80fe4",
} as const;
