// Generated by scripts/generate-version.sh at 2026-08-15T15:45:00Z — do not edit
export const BUILD_INFO = {
  commit: "eb35c5b417b19e5019e8abe6d46120a8cba1a385",
  short: "eb35c5b",
  describe: "eb35c5b-dirty",
  branch: "main",
  builtAt: "2026-08-15T15:45:00Z",
  builtHost: "macbook-pro.tail544547.ts.net",
  version: "0.3.0",
  message: "fix(paste): header inline like IRCCloud, details inline, actions inline",
  commitUrl: "https://github.com/kevinpostal/IRC_FIBER/commit/eb35c5b417b19e5019e8abe6d46120a8cba1a385",
} as const;
