// Generated by scripts/generate-version.sh at 2026-09-05T08:39:41Z — do not edit
export const BUILD_INFO = {
  commit: "857a1eabe40bbf108d0ba0860385ffe354ec21bc",
  short: "857a1ea",
  describe: "v0.3.0-106-g857a1ea",
  branch: "main",
  builtAt: "2026-09-05T08:39:41Z",
  builtHost: "Kevins-MacBook-Pro.local",
  version: "0.3.0",
  message: "chore: rebuild frontend bundles + version stamps",
  commitUrl: "https://github.com/kevinpostal/ircfiber-site/commit/857a1eabe40bbf108d0ba0860385ffe354ec21bc",
} as const;
