export const HELP: Record<string,string> = {
  width: 'Cells across; leave Height empty to keep aspect',
  height: 'Cells tall; empty keeps aspect ratio',
  font: 'Monospace used to measure glyph ink coverage',
  rasterSize: 'Glyph bitmap size in pixels; larger is sharper',
  sampling: 'How source pixels are sampled after resize',
  colourSpace: 'Perceptual distance used for palette matching',
  grayscaleTolerance: 'How strict gray detection is (0=strict)',
  glyphPreset: 'Quick palette of glyphs: Default (balanced), Smooth (dense), All (1588 chars)',
  glyphFind: 'Filter groups by name',
  glyphInclude: 'Only these characters can appear in output',
  glyphExclude: 'These characters will never appear',
  glyphIncludeRanges: 'Only codepoints in these hex ranges (e.g. 2600-26FF) — one per line',
  glyphExcludeRanges: 'Exclude codepoints in these hex ranges — one per line',
  braille: 'Use 2×4 dot Braille instead of half-blocks',
  brightness: 'Image brightness',
  contrast: 'Image contrast',
  gamma: 'Gamma correction',
  saturation: 'Colour saturation',
  hue: 'Hue rotation in degrees',
  rotation: 'Image rotation in degrees',
  hScale: 'Horizontal stretch',
  vScale: 'Vertical stretch',
  pixelize: 'Pixelation factor',
  gaussianBlur: 'Smooth blur before quantisation',
  dither: 'Error diffusion for palette',
  flipH: 'Mirror horizontally',
  flipV: 'Mirror vertically',
  invert: 'Invert colours',
  grayscale: 'Convert to grayscale',
  boxBlur: 'Simple box blur',
};
